# Generated by Django 2.2.12 on 2020-05-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desa',
            name='totalLaki',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='desa',
            name='totalPerempuan',
            field=models.IntegerField(default=0),
        ),
    ]
