# Generated by Django 2.2.12 on 2020-04-27 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anak',
            fields=[
                ('idAnak', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('nomorKMS', models.CharField(max_length=100)),
                ('tempatLahir', models.CharField(max_length=50)),
                ('tanggalLahir', models.CharField(max_length=12)),
                ('ibu', models.CharField(max_length=100)),
                ('desa', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DataPantau',
            fields=[
                ('idData', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField(auto_now=True)),
                ('tinggi', models.IntegerField(default=0)),
                ('berat', models.IntegerField(default=0)),
                ('vaksin', models.TextField()),
                ('asupan', models.TextField()),
                ('idAnak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anak.Anak')),
            ],
        ),
    ]
